model:
    class_path: models.models.mmclassifiers.MMClsModelAdapter
    init_args:
        model:
            class_path: models.models.mmclassifiers.ImageClassifier
            init_args:
                backbone:
                    type: MobileNetV2
                    widen_factor: 1.0
                neck:
                    type: GlobalAveragePooling
                head:
                    type: LinearClsHead
                    num_classes: 1000
                    in_channels: 1280
                    topk: !!python/tuple [1, 5]
                    loss:
                        type: CrossEntropyLoss
                        loss_weight: 1.0
