__base__: resnet50_transformer.yaml

model:
    init_args:
        model:
            class_path: models.models.mmclassifiers.ImageTransformerLearnLabelClassifier
            init_args:
                label_backbone:
                    __base__:
                        - [ resnet50.yaml, model.init_args.model.init_args.backbone ]
                label_loss:
                    type: CrossEntropyLoss
                    loss_weight: 0.1
                label_configs:
                    -   num_classes: 5
                    -   num_classes: 4
                    -   num_classes: 5
                        center_feature: false
                    -   num_classes: 4
                        center_feature: false