model:
    class_path: models.models.mmclassifiers.MMClsModelAdapter
    init_args:
        model:
            class_path: models.models.mmclassifiers.ImageClassifier
            init_args:
                backbone:
                    type: ResNet
                    depth: 50
                    frozen_stages: 1
                    norm_eval: true
                    num_stages: 4
                    out_indices: [3]
                    style: pytorch
                    norm_cfg:
                        requires_grad: true
                        type: BN
                    init_cfg:
                        checkpoint: torchvision://resnet50
                        type: Pretrained
                neck:
                    type: GlobalAveragePooling
                head:
                    type: LinearClsHead
                    num_classes: 1000
                    in_channels: 2048
                    topk: !!python/tuple [1, 5]
                    loss:
                        type: CrossEntropyLoss
                        loss_weight: 1.0
