__base__: resnet50.yaml

model:
    init_args:
        model:
            class_path: models.models.mmclassifiers.ImageDistillationLabelClassifier
            init_args:
                distillation_classifier:
                    __base__:
                        - [ resnet50.yaml, model.init_args.model ]
                    class_path: models.models.mmclassifiers.ImageDistillationLabelTeacherClassifier
                    init_args:
                        backbone:
                            out_indices: [ 0, 1, 2, 3 ]
                        head:
                            loss:
                                __delete__: true
                                type: NLLLoss
                                loss_weight: 1.0
                        init_cfg:
                            checkpoint: work_dirs/resnet50_with_label_cataract/72ltti3f/checkpoints/best.ckpt
                            type: Pretrained
                            prefix: model
                backbone:
                    out_indices: [ 0, 1, 2, 3 ]
                label_backbone:
                    type: ResNet
                    depth: 50
                    frozen_stages: 1
                    norm_eval: true
                    num_stages: 4
                    out_indices: [ 0, 1, 2, 3 ]
                    style: pytorch
                    norm_cfg:
                        requires_grad: true
                        type: BN
                    init_cfg:
                        checkpoint: torchvision://resnet50
                        type: Pretrained
                label_loss:
                    type: CrossEntropyLoss
                    loss_weight: 0.1
                label_configs:
                    -   num_classes: 5
                    -   num_classes: 5
                    -   num_classes: 4
                    -   num_classes: 5
                    -   num_classes: 5
                    -   num_classes: 4
                head:
                    loss:
                        __delete__: true
                        type: NLLLoss
                        loss_weight: 1.0
                distillation_loss:
                    type: SmoothL1Loss
                    loss_weight: 1.0