__base__:
    - resnet50_cataract.yaml
    - ../../models/image_classifier/resnet18_focal_loss.yaml

model:
    init_args:
        model:
            init_args:
                head:
                    num_classes: 7
